### ISSUE TITLE
`alloca` creates potentially unaligned reference to `MaybeUninit<T>`

### ISSUE THREAD

**Issue by playXE** [playXE/alloca-rs#1]
Found by matt1992 on Rust community discord server.

Potential solutions:
- Force alignment of stack allocated memory.
- Align `size_of::<T>` to 16 bytes.
- ... Maybe something else?

**Comment by cuviper** [comment]
You could use `size_of::<T>() + (align_of::<T>() - 1)` bytes for the raw allocation, then offset as needed for the final reference.

**Comment by playXE** [comment]
@cuviper thanks,I used your way and I belive this issue might be closed now. (https://github.com/playXE/alloca-rs/commit/085aa16786fb87109b150c5b51739a60729147a3)

**Comment by cuviper** [comment]
BTW, I think that commit added the file "f" in the root by mistake.

**Comment by playXE** [comment]
Yeah it did lol. Gonna fix it tomorrow,thanks for reminding. :)

чт, 28 янв. 2021 г., 21:32 Josh Stone <notifications@github.com>:
